url: "https://www.awesome-testing.com"
title: Awesome Testing
title_separator: "&#124;"
subtitle: ""
name: "Sławomir Radzymiński"
description: "Test automation blog, training and consultancy"
logo: /images/logo2.png
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num"
kramdown:
  syntax_highlighter: rouge
author_profile: true
author:
  name     : "Sławomir Radzymiński"
  avatar   : "/images/slawek.jpeg"
  bio      : "Senior Staff Test Engineer"
  location : "Kraków, Poland"
  links:
    - label: Email
      icon: "fas fa-fw fa-envelope"
      url: "mailto:slawomir.radzyminski@gmail.com"
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/slawekradzyminski/"
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "https://github.com/slawekradzyminski"
footer:
  links:
    - label: Email
      icon: "fas fa-fw fa-envelope"
      url: "mailto:slawomir.radzyminski@gmail.com"
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/slawekradzyminski/"
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "https://github.com/slawekradzyminski"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
google_analytics: "G-S9LYTKEDYY"
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
#jekyll-archives:
#  enabled:
#    - categories
#    - tags
#  layouts:
#    category: archive-taxonomy
#    tag: archive-taxonomy
#  permalinks:
#    category: /categories/:name/
#    tag: /tags/:name/
commentbox:
  id: 5697635910418432-proj
og_image: /images/logo2.png